name: ZAP with Playwright Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-test:
    runs-on: ubuntu-latest

    services:
      zap:
        image: owasp/zap2docker-stable:2.16.0
        ports:
          - 8080:8080
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        options: >-
          --entrypoint zap.sh
          -daemon -port 8080 -host 0.0.0.0 -config api.key=${{ secrets.ZAP_API_KEY }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Wait for ZAP to be ready
      - name: Wait for ZAP to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "ZAP is ready!"
              break
            else
              echo "Waiting for ZAP to start... (Attempt $i/20)"
              sleep 2
            fi
          done

      # Debug ZAP API
      - name: Debug ZAP API
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: |
          curl -s http://localhost:8080/JSON/core/view/version/?apikey=${{ secrets.ZAP_API_KEY }}

      # Run Playwright Security tests
      - name: Run Playwright Security tests
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          ZAP_URL: "http://localhost:8080"
        run: npm run security-test

      # Upload ZAP report as an artifact
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: ./Playwright-api-testing/security-report/
          if-no-files-found: error

      # Optional: Upload Playwright test results
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore