name: ZAP Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Install Java (required for ZAP)
      - name: Install Java
        run: sudo apt-get update && sudo apt-get install -y default-jre

      # Download and start ZAP
      - name: Start ZAP
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
          tar -xzf ZAP_2.16.0_Linux.tar.gz
          cd ZAP_2.16.0
          ./zap.sh -daemon -port 8080 -host 127.0.0.1 -config api.key=${{ secrets.ZAP_API_KEY }} &
          echo "ZAP started on port 8080"
          sleep 40 # Wait for ZAP to initialize

      # Debug: Check if ZAP is running
      - name: Check ZAP status
        run: |
          curl -s http://localhost:8080/JSON/core/view/version/?apikey=${{ secrets.ZAP_API_KEY }}

      - name: Create report directory
        run: mkdir -p security-report/    

      # Run Playwright tests with ZAP as the proxy
      - name: Run Playwright Security Tests
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
        run: npm run security-test

      - name: List files in report directory
        run: ls /home/runner/

      # Optional: Upload Playwright test results
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: /home/runner/2025-02-26-ZAP-Report-.html
          if-no-files-found: ignore