name: ZAP with Playwright Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start ZAP in daemon mode
      - name: Start ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
          tar -xzf ZAP_2.16.0_Linux.tar.gz
          cd ZAP_2.16.0
          ./zap.sh -daemon -port 8080 -host 127.0.0.1 -config api.key=${{ secrets.ZAP_API_KEY }} &
          echo "ZAP started on port 8080"

      # Wait for ZAP to be ready
      - name: Wait for ZAP to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "ZAP is ready!"
              break
            else
              echo "Waiting for ZAP to start... (Attempt $i/10)"
              sleep 5
            fi
          done

      # Run Playwright Security tests
      - name: Run Playwright Security tests
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          ZAP_URL: "http://localhost:8080"
        run: npm run security-test

      # Upload ZAP report as an artifact
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: ./Playwright-api-testing/security-report/
          if-no-files-found: error

      # Optional: Upload Playwright test results
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore
